[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
filterwarnings = [
  "error:::sqlalchemy_mptt"
]
addopts = "--cov sqlalchemy_mptt --cov-report term-missing:skip-covered"
