# -*- coding: utf-8 -*-
#
# sqlalchemy_mptt documentation build configuration file, created by
# sphinx-quickstart on Wed Jun 25 14:00:12 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.
from datetime import date
from docutils.parsers.rst import directives
from sphinx.directives.code import CodeBlock

directives.register_directive('no-code-block', CodeBlock)

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.mathjax',
    'sphinx.ext.mathbase',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'sqlalchemy_mptt'
copyright = '{}, uralbash'.format(date.today().year)

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output ----------------------------------------------

# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = 'sqlalchemy_mpttdoc'

html_theme_options = {
    'travis_button': True,
    'github_button': True,
    'github_user': 'uralbash',
    'github_repo': 'sqlalchemy_mptt',
}
